name: Code Coverage

on:
  pull_request:
    branches: 
      - master

jobs:
  cd:
    name: Code Covrage
    runs-on: ubuntu-latest
    steps:
      # - name: Configure private git
      #   env:
      #     REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}  # Replace with the name of your secret
      #   run: |
      #     git config --global user.email "you@example.com"
      #     git config --global user.name "Your Name"
      #     git remote set-url origin "https://github.com/username/private-repo.git"
      #     git fetch origin
      #     git checkout main
      #     git pull
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.14
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Execute Test
        id: execute_test
        run: |
          CVPKG=$(go list ./... | grep -v -e mocks -e cmd -e model -e scripts | tr '\n' ',')
          go test -coverpkg=${CVPKG} -coverprofile=coverage.out -covermode=count  ./...
          coverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
          echo "coverage=$coverage" >> $GITHUB_OUTPUT
      - name: Comment PR with code coverage
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            _Test Passed with Code Coverage: ${{ steps.execute_test.outputs.coverage }}_
          comment_tag: execution
